// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "sso/auth/api/internal/handler/auth"
	"sso/auth/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sign-in",
				Handler: auth.SignInHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/verify-token",
				Handler: auth.VerifyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sign-out",
				Handler: auth.SignOutHandler(serverCtx),
			},
		},
	)
}
