// Code generated by goctl. DO NOT EDIT!
// Source: auth.rpc.proto

package authclient

import (
	"context"

	"sso/service/auth/rpc/types/auth"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	TokenReq      = auth.TokenReq
	UserInfoReply = auth.UserInfoReply

	Auth interface {
		GetUser(ctx context.Context, in *TokenReq, opts ...grpc.CallOption) (*UserInfoReply, error)
	}

	defaultAuth struct {
		cli zrpc.Client
	}
)

func NewAuth(cli zrpc.Client) Auth {
	return &defaultAuth{
		cli: cli,
	}
}

func (m *defaultAuth) GetUser(ctx context.Context, in *TokenReq, opts ...grpc.CallOption) (*UserInfoReply, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}
