// Code generated by goctl. DO NOT EDIT.

export interface Option {
	label: string
	value: string
	extra?: string
}

export interface SignInReq {
	mobile: string
	password: string
	remember: boolean
}

export interface SignInReply {
	accessToken: string
	uuid: string
	name: string
	mobile: string
	avatar: string
	gender: number
	roles: Array<Option>
}

export interface SignOutReply {
	success: boolean
}

export interface VerifyTokenReply {
	userId: number
	success: boolean
}

