// Code generated by goctl. DO NOT EDIT.
package types

type Option struct {
	Label string `json:"label"`
	Value string `json:"value"`
	Extra string `json:"extra,optional"`
}

type SignInReq struct {
	SystemCode string `json:"systemCode"`
	Mobile     string `json:"mobile"`
	Password   string `json:"password"`
	Remember   string `json:"remember,optional"`
}

type SignInReply struct {
	AccessToken string   `json:"accessToken"`
	Redirect    string   `json:"redirect"`
	Name        string   `json:"name"`
	Mobile      string   `json:"mobile"`
	Avatar      string   `json:"avatar"`
	Gender      int64    `json:"gender"`
	Expire      int64    `json:"expire"`
	Roles       []Option `json:"roles"`
}

type SignOutReply struct {
	Success bool `json:"success"`
}

type VerifyRequestReq struct {
	Token       string `json:"token"`
	SystemCode  string `json:"systemCode"`
	ServiceCode string `json:"serviceCode"`
	URI         string `json:"uri"`
	Method      string `json:"method"`
	MenuURI     string `json:"menuURI"`
}

type VerifyRequestReply struct {
	UUID string `json:"uuid"`
	Name string `json:"name"`
}

type Meta struct {
	Name       string   `json:"n"` // 菜单名
	Icon       string   `json:"i"` // 菜单icon
	Identifier string   `json:"u"` // 唯一标识符
	SubType    int64    `json:"t"` // 菜单类型，1菜单，2菜单组, 3隐藏菜单
	Parents    []string `json:"p"` // 所有父级菜单uuid
}

type Menu struct {
	UUID     string  `json:"n"` // 路由命名
	Key      string  `json:"p"` // 路由路径
	Meta     Meta    `json:"m"` // 路由meat
	Children []*Menu `json:"c"` // 路由children
	PUUID    string  `json:"-"`
}

type SessionMenusReply struct {
	List []*Menu `json:"list"`
}
