// Code generated by goctl. DO NOT EDIT.

export interface StsReq {
}
export interface StsReqParams {
	bucket: string // bucket
}

export interface StsReply {
	region: string
	endpoint: string
	bucket: string
	accessKeyId: string
	accessKeySecret: string
	stsToken: string
}

