// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	object "sso/ssoms/api/internal/handler/object"
	permission "sso/ssoms/api/internal/handler/permission"
	role "sso/ssoms/api/internal/handler/role"
	user "sso/ssoms/api/internal/handler/user"
	"sso/ssoms/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user",
				Handler: user.UserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user",
				Handler: user.AddUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/:uuid",
				Handler: user.UserDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/:uuid",
				Handler: user.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/:uuid",
				Handler: user.DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/filterOptions",
				Handler: user.UserFilterOptionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/assignedRoles",
				Handler: user.AssignedRolesHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/assignRole",
				Handler: user.AssignRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/permissions",
				Handler: user.UserPermissionsHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/role",
				Handler: role.RoleListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role",
				Handler: role.AddRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/role/:roleUUID",
				Handler: role.RoleDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/role/:roleUUID",
				Handler: role.UpdateRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/role/:roleUUID",
				Handler: role.DeleteRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/role/options",
				Handler: role.RoleOptionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/assignedUsers",
				Handler: role.AssignedUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/role/:roleUUID/assignUser",
				Handler: role.AssignUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/role/:roleUUID/deassignUser",
				Handler: role.DeassignUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/role/:roleUUID/inheritances",
				Handler: role.InheritancesHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/role/:roleUUID/addInheritance",
				Handler: role.ExtendRoleHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/object",
				Handler: object.ObjectListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/object",
				Handler: object.AddObjectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/object/:uuid",
				Handler: object.ObjectDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/object/:uuid",
				Handler: object.UpdateObjectHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/object/:uuid",
				Handler: object.DeleteObjectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/object/roleOperations",
				Handler: object.RoleOperationsHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/role/:roleUUID/Permissions",
				Handler: permission.RolePermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/grant",
				Handler: permission.GrantHandler(serverCtx),
			},
		},
		rest.WithPrefix("/permission"),
	)
}
