// Code generated by goctl. DO NOT EDIT.
package types

type Option struct {
	Label string `json:"label"`
	Value string `json:"value"`
	Extra string `json:"extra,optional"`
}

type SignInReq struct {
	SystemCode string `json:"systemCode"`
	Mobile     string `json:"mobile"`
	Password   string `json:"password"`
	Remember   string `json:"remember,optional"`
}

type SignInReply struct {
	AccessToken string   `json:"accessToken"`
	Redirect    string   `json:"redirect"`
	Name        string   `json:"name"`
	Mobile      string   `json:"mobile"`
	Avatar      string   `json:"avatar"`
	Gender      int64    `json:"gender"`
	Expire      int64    `json:"expire"`
	Roles       []Option `json:"roles"`
}

type SignOutReply struct {
	Success bool `json:"success"`
}

type VerifyRequestReq struct {
	Token       string `json:"token"`
	SystemCode  string `json:"systemCode"`
	ServiceCode string `json:"serviceCode"`
	URI         string `json:"uri"`
}

type VerifyRequestReply struct {
	UUID string `json:"uuid"`
	Name string `json:"name"`
}
