// Code generated by goctl. DO NOT EDIT.
package types

type Option struct {
	Label string `json:"label"`
	Value string `json:"value"`
	Extra string `json:"extra,optional"`
}

type SignInReq struct {
	ServiceCode string `json:"serviceCode"`
	Mobile      string `json:"mobile"`
	Password    string `json:"password"`
	Remember    string `json:"remember,optional"`
}

type SignInReply struct {
	AccessToken string   `json:"accessToken"`
	Redirect    string   `json:"redirect"`
	Name        string   `json:"name"`
	Mobile      string   `json:"mobile"`
	Avatar      string   `json:"avatar"`
	Gender      int64    `json:"gender"`
	Roles       []Option `json:"roles"`
}

type SignOutReply struct {
	Success bool `json:"success"`
}

type VerifyTokenReply struct {
	UserId  int64 `json:"userId"`
	Success bool  `json:"success"`
}
