// Code generated by goctl. DO NOT EDIT.

export interface Option {
	label: string
	value: string
	extra?: string
}

export interface SignInReq {
	systemCode: string
	mobile: string
	password: string
	remember?: string
}

export interface SignInReply {
	accessToken: string
	redirect: string
	name: string
	mobile: string
	avatar: string
	gender: number
	expire: number
	roles: Array<Option>
}

export interface SignOutReply {
	success: boolean
}

export interface VerifyRequestReq {
	token: string
	systemCode: string
	serviceCode: string
	uri: string
}

export interface VerifyRequestReply {
	uuid: string
	name: string
}

export interface SessionMenusReq {
	token: string
	systemCode: string
}

export interface Meta {
	n: string // 菜单名
	i: string // 菜单icon
	u: string // 唯一标识符
	t: number // 菜单类型，1菜单，2菜单组, 3隐藏菜单
}

export interface Menu {
	n: string // 路由命名
	p: string // 路由路径
	m: Meta // 路由meat
	c: Array<Menu> // 路由children
	pUUID: string
}

export interface SessionMenusReply {
	list: Array<Menu>
}

