// Code generated by goctl. DO NOT EDIT.
package types

type Option struct {
	Label string `json:"label"`
	Value string `json:"value"`
	Extra string `json:"extra,optional"`
}

type UserListReq struct {
	Name     string `form:"name,optional"`
	Mobile   string `form:"mobile,optional"`
	Page     int64  `form:"page"`
	PageSize int64  `form:"pageSize,default=20"`
}

type User struct {
	UUID   string   `json:"uuid"`
	Name   string   `json:"name"`
	Mobile string   `json:"mobile"`
	Avatar string   `json:"avatar"`
	Gender int64    `json:"gender"`
	Status int64    `json:"status"`
	Roles  []Option `json:"roles"`
}

type UserListReply struct {
	Total int64  `json:"total"`
	List  []User `json:"list"`
}

type AddUserReq struct {
	Name     string `form:"name"`
	Mobile   string `form:"mobile"`
	Password string `form:"password"`
	Avatar   string `form:"avatar"`
	Gender   int64  `form:"gender"`
	Birth    string `form:"birth"`
	Status   int64  `form:"status,default=1"`
}

type AddUserReply struct {
	UUID string `json:"uuid"`
}

type UserDetailReq struct {
	UUID string `form:"uuid"`
}

type UserDetailReply struct {
	UUID     string `json:"uuid"`
	Name     string `json:"name"`
	Mobile   string `json:"mobile"`
	Avatar   string `json:"avatar"`
	Gender   int64  `json:"gender"`
	Birth    string `json:"birth"`
	Status   int64  `json:"status"`
	Password string `json:"password"`
}

type UpdateUserReq struct {
	UUID     string `form:"uuid"`
	Name     string `form:"name"`
	Mobile   string `form:"mobile"`
	Password string `form:"password,optional"`
	Avatar   string `form:"avatar"`
	Gender   int64  `form:"gender"`
	Birth    string `form:"birth"`
	Status   int64  `form:"status,default=1"`
}

type UpdateUserReply struct {
	Success bool `json:"success"`
}

type DeleteUserReq struct {
	UUID string `form:"uuid"`
}

type DeleteUserReply struct {
	Success bool `json:"success"`
}

type UserFilterOptionsReq struct {
	Name string `json:"name"`
}

type UserFilterOptionsReply struct {
	Options []Option `json:"options"`
}

type AssignedRolesReq struct {
	UUID string `form:"uuid"`
}

type AssignedRolesReply struct {
	Roles []Option `json:"roles"`
}

type AssignRoleReq struct {
	UUID          string   `form:"uuid"`
	RoleUUIDArray []string `form:"roleUUIDArray"`
}

type AssignRoleReply struct {
	Success bool `json:"success"`
}

type UserPermissionsReq struct {
	UUID string `form:"uuid"`
	Typ  int64  `form:"type"` // 类型: 角色
}

type UserPermissionsReply struct {
	Systems []Option `json:"system"`
}

type RoleListReq struct {
	RoleName string `form:"roleName,optional"`
	Page     int64  `form:"page"`
	PageSize int64  `form:"pageSize,default=20"`
}

type Role struct {
	RoleUUID     string   `json:"roleUUID"`     // 角色uuid
	RoleName     string   `json:"roleName"`     // 角色名称
	Summary      string   `json:"summary"`      // 角色概述
	Inheritances []Option `json:"inheritances"` // 继承的角色
	UsersAmount  int64    `json:"usersAmount"`  // 拥有的用户数量
}

type RoleListReply struct {
	Total int64  `json:"total"`
	List  []Role `json:"list"`
}

type AddRoleReq struct {
	RoleName string `form:"roleName"`
	Summary  string `form:"summary"`
}

type AddRoleReply struct {
	RoleUUID string `json:"roleUUID"`
}

type RoleDetailReq struct {
	RoleUUID string `form:"roleUUID"`
}

type RoleDetailReply struct {
	RoleUUID string `json:"roleUUID"`
	RoleName string `json:"roleName"`
	Summary  string `json:"summary"`
}

type UpdateRoleReq struct {
	RoleUUID string `form:"roleUUID"`
	RoleName string `form:"roleName"`
	Summary  string `form:"summary"`
}

type UpdateRoleReply struct {
	Success bool `json:"success"`
}

type DeleteRoleReq struct {
	RoleUUID string `form:"roleUUID"`
}

type DeleteRoleReply struct {
	Success bool `json:"success"`
}

type OptionsReply struct {
	Options []Option `json:"options"`
}

type AssignedUsersReq struct {
	RoleUUID string `form:"roleUUID"`
}

type AssignedUsersReply struct {
	User []Option `json:"users"`
}

type AssignUserReq struct {
	RoleUUID string `form:"roleUUID"`
	UserUUID string `form:"userUUID"`
}

type AssignUserReply struct {
	Success bool `json:"success"`
}

type InheritancesReq struct {
	RoleUUID string `form:"roleUUID"`
}

type InheritancesReply struct {
	Roles []Option `json:"roles"`
}

type AddInheritanceReq struct {
	RoleUUID                string   `form:"roleUUID"`
	AddInheritanceUUIDArray []string `form:"extendedRoleUUIDArray"`
}

type AddInheritanceReply struct {
	Success bool `json:"success"`
}

type ObjectListReq struct {
	ObjectName string `form:"objectName,optional"`
	Key        string `form:"key,optional"`
}

type Object struct {
	UUID       string   `json:"uuid"`
	ObjectName string   `json:"objectName"`
	Domain     string   `json:"domain"`
	Key        string   `json:"key"` // 操作对象的systemCode, 菜单的path, 操作的uri
	Sort       int64    `json:"sort"`
	Typ        int64    `json:"type"` // 类型, 1操作对象, 2模块，3菜单组，4菜单，5操作(接口)
	Icon       string   `json:"icon"` // 图标
	Status     int64    `json:"status"`
	PUUID      string   `json:"pUUID,optional"`
	Children   []Object `json:"children,optional"`
}

type ObjectListReply struct {
	List []Object `json:"list"`
}

type AddObjectReq struct {
	ObjectName string `form:"objectName"`
	Domain     string `form:"domain"`
	Key        string `form:"key"` // 操作对象的systemCode, 菜单的path, 操作的uri
	Sort       int64  `form:"sort"`
	Typ        int64  `form:"type"` // 类型, 1操作对象, 2模块，3菜单组，4菜单，5操作(接口)
	Icon       string `form:"icon"` // 图标
	Status     int64  `form:"status"`
	PUUID      string `form:"pUUID,optional"`
}

type AddObjectReply struct {
	UUID string `json:"uuid"`
}

type ObjectDetailReq struct {
	UUID string `form:"uuid"`
}

type ObjectDetailReply struct {
	UUID       string `json:"uuid"`
	ObjectName string `json:"objectName"`
	Domain     string `json:"domain"`
	Key        string `json:"key"` // 操作对象的systemCode, 菜单的path, 操作的uri
	Sort       int64  `json:"sort"`
	Typ        int64  `json:"type"` // 类型, 1操作对象, 2模块，3菜单组，4菜单，5操作(接口)
	Icon       string `json:"icon"` // 图标
	Status     int64  `json:"status"`
	PUUID      string `json:"pUUID,optional"`
}

type UpdateObjectReq struct {
	ObjectName string `form:"objectName"`
	Domain     string `form:"domain"`
	Key        string `form:"key"` // 操作对象的systemCode, 菜单的path, 操作的uri
	Sort       int64  `form:"sort"`
	Typ        int64  `form:"type"` // 类型, 1操作对象, 2模块，3菜单组，4菜单，5操作(接口)
	Icon       string `form:"icon"` // 图标
	Status     int64  `form:"status"`
	PUUID      string `form:"pUUID,optional"`
}

type UpdateObjectReply struct {
	Success bool `json:"success"`
}

type DeleteObjectReq struct {
	UUID string `form:"uuid"`
}

type DeleteObjectReply struct {
	Success bool `json:"success"`
}

type RoleOperationsReq struct {
	TypeName string `form:"typeName"` // system, others
	PUUID    string `form:"pUUID,optional"`
}

type RoleOperationsReply struct {
	List []Object `json:"list,optional"`
}

type RolePermissionsReq struct {
	TypeName string `form:"typeName"` // system, others
	PUUID    string `form:"pUUID,optional"`
}

type ObjectOption struct {
	Label    string         `json:"label"`
	Value    string         `json:"value"`
	Typ      int64          `json:"type"` // 类型, 1操作对象, 2模块，3菜单组，4菜单，5操作(接口)
	Extra    string         `json:"extra"`
	Children []ObjectOption `json:"children"`
}

type RolePermissionsReply struct {
	List []ObjectOption `json:"list"`
}

type GrantReq struct {
	TypeName string `form:"typeName"` // system, others
	PUUID    string `form:"pUUID,optional"`
}

type GrantReply struct {
	UUIDArray []string `json:"uuidArray"`
}
