// Code generated by goctl. DO NOT EDIT!
// Source: auth.rpc.proto

package server

import (
	"context"

	"sso/service/auth/rpc/internal/logic"
	"sso/service/auth/rpc/internal/svc"
	"sso/service/auth/rpc/types/auth"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServer) GetUser(ctx context.Context, in *auth.TokenReq) (*auth.UserInfoReply, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
